### ISSUE TITLE
Export to XLIFF crashes with ruby error

### ISSUE THREAD

**Issue by pnull** [phrase/PhraseAppXcode#5] opened 2016-06-27 07:52 UTC
What can i do to work around this issue?

```
# Export to XLIFF
/Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:65:in `prettyPrintXcodeBuildLine': undefined method `start_with?' for nil:NilClass (NoMethodError)
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:55:in `block (2 levels) in callXcodeBuild'
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:55:in `each_line'
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:55:in `block in callXcodeBuild'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:49:in `callXcodeBuild'
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:84:in `run'
    from /Users/pb/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PhraseAppXcodePlugin.xcplugin/Contents/Resources/phraseapp_xliff.rb:131:in `<main>'
```

**Comment by sacry-dyn** [comment] 2016-06-27 08:01
@pnull we are currently working on finding the root cause for this (we are actively tracking it as a ticket). It seems that some xliff files differ in their formatting and it crashes due to some nil pointer exception. However it is a bit early to fully verify what the problem is. A sample file (the one which caused the issue) would help a lot.

**Comment by pnull** [comment] 2016-06-27 08:19
I digged a bit deeper into the problem and it seems that the/a `genstrings` call doesn't exit nicely. Is there a way to exclude files from being piped through `genstrings`? or - in our case much better - disable calling `genstrings` alltogether?

**Comment by sacry-dyn** [comment] 2016-06-27 10:35
The plugin for Xcode is currently specifically designed to work with import and export. We currently then suggest that you use the phraseapp-client from your terminal and import/export as you like https://github.com/phrase/phraseapp-client

However we will think about the current limitations and see if we find a good solution (maybe with a simple flag that disables export/import entirely)

**Comment by sacry-dyn** [comment] 2016-07-25 09:25
@pnull we have currently something in the pipeline. We fixed the nil pointer but also added the possibility to skip import/export entirely. It is currently in review and hopefully released soon.

**Comment by sacry-dyn** [comment] 2016-07-25 12:12
@pnull update on this: https://github.com/phrase/PhraseAppXcode/releases/tag/1.1.0

**Comment by sacry-dyn** [comment] 2016-07-27 09:35
@pnull I will close this for now. If anything comes up again, feel free to reopen or open another issue

**Closed as completed by sacry-dyn** 2016-07-27 09:35 UTC
